FROM jenkins/jenkins:2.426.1-lts

# Switch to root user to install plugins
USER root

# Copy plugins.txt file
COPY jenkins/plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install plugins using jenkins-plugin-cli (the new official method)
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt --verbose

# Switch back to jenkins user
USER jenkins

# Skip initial setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"