version: '3.8'

services:
  # OWASP Dependency Track - API Server
  dependency-track-apiserver:
    image: dependencytrack/apiserver:4.10.1
    container_name: dt-apiserver
    environment:
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://postgres:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtrack
      - ALPINE_DATABASE_PASSWORD=changeme
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=20
      - ALPINE_DATABASE_POOL_MIN_IDLE=10
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
      - ALPINE_SECRET_KEY_PATH=/var/run/secrets
      - ALPINE_DATA_DIRECTORY=/data
      - ALPINE_CORS_ENABLED=true
      - ALPINE_CORS_ALLOW_ORIGIN=http://localhost:8081
      - ALPINE_CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ALPINE_CORS_ALLOW_HEADERS=Origin,Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,X-Api-Key
      - ALPINE_CORS_EXPOSE_HEADERS=Content-Type,X-Api-Key
    volumes:
      - 'dt-data:/data'
      - 'dt-tmp:/tmp'
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - mend-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # OWASP Dependency Track - Frontend
  dependency-track-frontend:
    image: dependencytrack/frontend:4.10.1
    container_name: dt-frontend
    environment:
      - API_BASE_URL=http://localhost:8081
    ports:
      - "8082:8080"
    restart: unless-stopped
    depends_on:
      - dependency-track-apiserver
    networks:
      - mend-network

  # PostgreSQL Database for Dependency Track
  postgres:
    image: postgres:15-alpine
    container_name: dt-postgres
    environment:
      - POSTGRES_DB=dtrack
      - POSTGRES_USER=dtrack
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    restart: unless-stopped
    networks:
      - mend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dtrack -d dtrack"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Jenkins
  jenkins:
    image: jenkins/jenkins:2.426.1-lts
    container_name: jenkins
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xmx2g
      - JENKINS_OPTS=--httpPort=8080
      - DT_API_KEY=${DT_API_KEY}
      - DT_API_URL=${DT_API_URL}
    volumes:
      - 'jenkins-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt'
      - './jenkins/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d'
      - './jenkins/jobs:/usr/share/jenkins/ref/jobs'
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
    networks:
      - mend-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Maven for building (optional helper container)
  maven:
    image: maven:3.9.5-openjdk-11
    container_name: maven-helper
    volumes:
      - 'maven-repo:/root/.m2'
      - './workspace:/workspace'
    working_dir: /workspace
    networks:
      - mend-network
    profiles:
      - tools

volumes:
  dt-data:
    driver: local
  dt-tmp:
    driver: local
  postgres-data:
    driver: local
  jenkins-data:
    driver: local
  maven-repo:
    driver: local

networks:
  mend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16